# Generated by Django 4.2.6 on 2023-10-25 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_person_alter_mainthread_user_alter_thread_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainthread',
            name='user',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='user',
        ),
        migrations.AddField(
            model_name='mainthread',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.person'),
        ),
        migrations.AddField(
            model_name='thread',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.person'),
        ),
    ]
