# Generated by Django 4.2.6 on 2023-10-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_book_readingprogress_quizpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='review',
            field=models.TextField(default='s'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
