# Generated by Django 4.2.6 on 2023-10-28 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_book_readingprogress'),
        ('main', '0005_book_readingprogress_quizpoint'),
    ]

    operations = [
    ]
