# Generated by Django 4.2.6 on 2023-10-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_readingprogress_rating_readingprogress_review_and_more'),
        ('main', '0007_readingprogress_rating_readingprogress_review_and_more'),
    ]

    operations = [
    ]
