# Generated by Django 4.2.6 on 2023-10-29 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231026_2231'),
        ('main', '0008_merge_20231028_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingprogress',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='review',
            field=models.TextField(default=''),
        ),
    ]
