# Generated by Django 4.2.6 on 2023-10-29 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_readingprogress_bookstore'),
        ('main', '0008_merge_20231028_2234'),
    ]

    operations = [
    ]
