# Generated by Django 4.2.6 on 2023-10-29 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231026_2231'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_merge_20231029_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='review',
            field=models.TextField(default='s'),
        ),
        migrations.AlterField(
            model_name='readingprogress',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
