# Generated by Django 4.2.6 on 2023-10-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_readingprogress_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingprogress',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='image',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='title',
            field=models.CharField(default='', max_length=256),
        ),
    ]
